version: "3.3"
services:
  sentc_file_worker:
    image: sentc/file_worker:${SENTC_FILE_WORKER_VERSION}
    restart: always
    command: sh -c "sleep 20 && /sentc_api_init && /file_worker"
    env_file:
      - ../sentc.env
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DB}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      LOCAL_STORAGE_PATH: /var/www/storage
      LOCAL_KEY_STORAGE: /var/www/storage_key
    volumes:
      - ../storage:/var/www/storage
      - ../storage_key:/var/www/storage_key